replicaCount: 3
environment: PROD
image:
  repository: 192.168.18.53/payment/payment-api
  tag: 1.0.1-rc1-TEST-3c88828-3
  digest: sha256:dbbd37fb28711dd4d42dcff0b0a466c8eafb677f29fadcb8a90a478b7b65a370
service:
  type: NodePort
  port: 8080
  nodePort: 30082
ingress:
  enabled: false
  host: payment-api.bank.local
