replicaCount: 1
environment: DEV
image:
  repository: 192.168.18.53/payment/payment-api
  tag: 0.0.0-dev-DEV-08578f6-19
  digest: sha256:23253d500afde270d38be2ae50c07cb87d209521bc3d5bd5729f9d23573ebc49
service:
  type: NodePort
  port: 8080
  nodePort: 30080
ingress:
  enabled: false
  host: payment-api.dev.bank.local
