replicaCount: 3
environment: PROD
image:
  repository: 192.168.18.53/payment/payment-api
  tag: 0.0.0-dev-DEV-2009760-10
  digest: ""
service:
  type: NodePort
  port: 8080
  nodePort: 30082
ingress:
  host: payment-api.bank.local
