replicaCount: 2
environment: TEST
image:
  repository: 192.168.18.53/payment/payment-api
  tag: 0.0.0-dev-DEV-2009760-10
  digest: ""
service:
  type: NodePort
  port: 8080
  nodePort: 30081
ingress:
  enabled: false
  host: payment-api.test.bank.local
