replicaCount: 1
environment: DEV
image:
  repository: 192.168.18.53/payment/payment-api
  tag: 0.0.0-dev-DEV-99dd357-12
  digest: 
service:
  type: NodePort
  port: 8080
  nodePort: 30080
ingress:
  host: payment-api.dev.bank.local
