replicaCount: 2
environment: TEST
image:
  repository: 192.168.18.53/payment/payment-api
  tag: v1.2.2
  digest: sha256:dd1e38d5c94ea8541c51d98fefe49b4cb37fd0194ebd4faaef6b6e74a8d523d8
service:
  type: NodePort
  port: 8080
  nodePort: 30081
ingress:
  enabled: false
  host: payment-api.test.bank.local
