replicaCount: 3
environment: PROD
image:
  repository: 192.168.18.53/payment/payment-api
  tag: v1.1.1
  digest: sha256:2973bacffc1ec128271ff8228f7d2212ae5536456e408bf8302922bca8018702
service:
  type: NodePort
  port: 8080
  nodePort: 30082
ingress:
  enabled: false
  host: payment-api.bank.local
