replicaCount: 1
environment: DEV
image:
  repository: 192.168.18.53/payment/payment-api
  tag: payment-api-DEV-0916d22-21
  digest: sha256:f5f4486ee1e11b0b064b195635b6546a6f673b0f6de22810edc7ef120ac3ccdb
service:
  type: NodePort
  port: 8080
  nodePort: 30080
ingress:
  enabled: false
  host: payment-api.dev.bank.local
