name: Jira PROD Deploy

on:
  repository_dispatch:
    types: [jira-prod-deploy]
  workflow_dispatch:
    inputs:
      jira_issue_key:
        required: true
        type: string
      release_version:
        required: true
        type: string
      deployment_type:
        required: true
        type: choice
        options: [iis, kubernetes]

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  prod:
    uses: yazicigurkan/bank-devsecops-pipeline-platform/.github/workflows/dotnet-jira-prod-release.yaml@v1.0.19
    with:
      jira_issue_key: ${{ github.event.inputs.jira_issue_key || github.event.client_payload.jira_issue_key }}
      application_name: ${{ github.event.client_payload.application_name || 'payment-api' }}
      repository_name: ${{ github.event.client_payload.repository_name || github.event.repository.name }}
      branch_name: PROD
      release_version: ${{ github.event.inputs.release_version || github.event.client_payload.release_version }}
      deployment_type: ${{ github.event.inputs.deployment_type || github.event.client_payload.deployment_type }}
      target_environment: PROD
      nexus_repository: dotnet-releases
      harbor_registry: 192.168.18.53
      harbor_project: payment
      image_name: payment-api
      k8s_namespace: payment-prod
      helm_chart_path: deploy/k8s/chart
      helm_values_file: deploy/k8s/values-prod.yaml
      iis_server_group: IIS_PROD_PAYMENT
      iis_site_name: Payment.Api
      iis_app_pool_name: Payment.Api
      deploy_path: D:\Sites\Payment.Api
      health_check_url: https://payment-api.bank.local/health
      rollback_enabled: true
    secrets: inherit
