<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Payment.Api</AssemblyName>
    <RootNamespace>Payment.Api</RootNamespace>
  </PropertyGroup>
</Project>
